In [26]:
import pandas as pd
import importlib
import sys
sys.path.append('../src')
import data
importlib.reload(data)
from data import save_data, load_data, manipulate_data, check_for_na, check_data_type, test_unit_dtype, test_unit_less_than_or_greater_than, test_unit_between

In [27]:
df_USA_2018_2019 = load_data('../data/raw/USACPI_2018_2019.csv')
df_Canada_2018_2019 = load_data('../data/raw/CanadaCPI_2018_2019.csv')

In [28]:
df_USA_2018_2019.head(20)

,ITEM,TITLE,series id,DATA TYPE,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
0,SA0,All items,CUSR0000SA0,SEASONALLY ADJUSTED INDEX,2018,248.859,249.529,249.577,250.227,250.792,251.018,251.214,251.663,252.182,252.772,252.594,252.767
1,SA0,All items,CUSR0000SA0,SEASONALLY ADJUSTED INDEX,2019,252.718,253.322,254.202,255.211,255.290,255.159,255.685,256.059,256.511,257.244,257.803,258.616
2,SA0,All items,CUSR0000SA0,SEASONAL FACTOR,2018,99.601,99.784,99.991,100.127,100.317,100.387,100.315,100.192,100.102,100.045,99.780,99.393
3,SA0,All items,CUSR0000SA0,SEASONAL FACTOR,2019,99.602,99.784,100.000,100.132,100.314,100.386,100.347,100.195,100.097,100.040,99.769,99.365
4,SA0,All items,CUSR0000SA0,UNADJUSTED INDEX,2018,247.867,248.991,249.554,250.546,251.588,251.989,252.006,252.146,252.439,252.885,252.038,251.233
5,SA0,All items,CUSR0000SA0,UNADJUSTED INDEX,2019,251.712,252.776,254.202,255.548,256.092,256.143,256.571,256.558,256.759,257.346,257.208,256.974
6,SA0E,Energy,CUSR0000SA0E,SEASONALLY ADJUSTED INDEX,2018,216.855,220.141,215.720,219.165,221.045,220.947,219.929,222.781,223.955,226.022,218.500,213.630
7,SA0E,Energy,CUSR0000SA0E,SEASONALLY ADJUSTED INDEX,2019,206.808,209.143,214.305,222.300,219.682,213.339,215.128,213.335,213.647,216.546,217.228,221.757
8,SA0E,Energy,CUSR0000SA0E,SEASONAL FACTOR,2018,97.145,96.992,98.532,99.847,102.608,103.707,103.264,101.866,100.987,99.883,98.815,96.384
9,SA0E,Energy,CUSR0000SA0E,SEASONAL FACTOR,2019,96.980,96.938,98.796,100.090,102.773,103.766,103.423,101.708,100.829,99.910,98.807,96.043
10,SA0E,Energy,CUSR0000SA0E,UNADJUSTED INDEX,2018,210.663,213.519,212.554,218.830,226.810,229.137,227.107,226.939,226.165,225.757,215.910,205.905
11,SA0E,Energy,CUSR0000SA0E,UNADJUSTED INDEX,2019,200.563,202.740,211.724,222.499,225.773,221.373,222.492,216.978,215.418,216.351,214.636,212.982
12,SA0L1,All items less food,CUSR0000SA0L1,SEASONALLY ADJUSTED INDEX,2018,248.301,249.089,249.128,249.801,250.452,250.666,250.826,251.291,251.834,252.534,252.220,252.270
13,SA0L1,All items less food,CUSR0000SA0L1,SEASONALLY ADJUSTED INDEX,2019,252.117,252.695,253.644,254.858,254.878,254.715,255.301,255.702,256.132,256.888,257.440,258.297
14,SA0L1,All items less food,CUSR0000SA0L1,SEASONAL FACTOR,2018,99.541,99.751,99.990,100.127,100.352,100.442,100.355,100.213,100.112,100.040,99.777,99.340
15,SA0L1,All items less food,CUSR0000SA0L1,SEASONAL FACTOR,2019,99.547,99.755,100.000,100.132,100.346,100.436,100.386,100.214,100.105,100.033,99.767,99.310
16,SA0L1,All items less food,CUSR0000SA0L1,UNADJUSTED INDEX,2018,247.161,248.469,249.102,250.117,251.333,251.775,251.716,251.827,252.116,252.636,251.657,250.605
17,SA0L1,All items less food,CUSR0000SA0L1,UNADJUSTED INDEX,2019,250.974,252.077,253.643,255.194,255.759,255.825,256.286,256.250,256.401,256.973,256.839,256.516
18,SA0L12,All items less food and shelter,CUSR0000SA0L12,SEASONALLY ADJUSTED INDEX,2018,224.497,225.385,224.982,225.551,226.008,226.152,225.995,226.242,226.799,227.421,226.586,226.262
19,SA0L12,All items less food and shelter,CUSR0000SA0L12,SEASONALLY ADJUSTED INDEX,2019,225.650,226.014,226.924,228.179,227.825,227.210,227.691,228.005,228.176,229.074,229.538,230.497

In [29]:
df_USA_2018_2019.sample(20)

,ITEM,TITLE,series id,DATA TYPE,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
482,SEAE02,Boys' and girls' footwear,CUSR0000SEAE02,SEASONAL FACTOR,2018,98.461,99.817,100.797,101.059,99.547,98.539,99.264,100.222,100.891,101.688,100.444,98.768
918,SEHE02,"Propane, kerosene, and firewood",CUSR0000SEHE02,SEASONALLY ADJUSTED INDEX,2018,338.587,336.850,337.316,340.030,341.588,341.919,342.165,345.237,346.632,344.759,340.878,336.374
842,SEFT02,Frozen and freeze dried prepared foods,CUSR0000SEFT02,SEASONAL FACTOR,2018,98.785,99.382,99.241,100.412,100.406,100.507,100.773,100.095,99.969,100.178,100.101,100.157
1697,SAS367,Other services,CWSR0000SAS367,UNADJUSTED INDEX,2019,329.260,329.929,330.149,330.425,330.093,330.504,330.801,331.827,332.269,333.377,334.522,335.345
1100,SERE,Other recreational goods,CUSR0000SERE,SEASONAL FACTOR,2018,100.698,101.147,100.727,100.515,100.330,100.003,99.222,99.395,99.776,99.832,99.310,99.127
1840,SEAG02,Jewelry,CWSR0000SEAG02,UNADJUSTED INDEX,2018,173.318,177.019,180.894,176.489,175.947,173.211,177.998,175.232,172.453,167.900,164.670,161.238
1461,SAE,Education and communication,CWSR0000SAE,SEASONAL FACTOR,2019,100.031,100.029,99.936,99.880,99.852,99.863,99.845,100.018,100.188,100.174,100.122,100.056
1204,SS04031,"Ham, excluding canned",CUSR0000SS04031,UNADJUSTED INDEX,2018,217.279,212.758,221.476,216.168,224.579,230.981,230.339,227.895,232.358,228.307,224.053,213.719
869,SEFW,Alcoholic beverages at home,CUSR0000SEFW,UNADJUSTED INDEX,2019,204.723,206.233,205.315,204.671,205.415,205.693,205.990,206.297,205.950,206.087,205.127,204.376
312,SANL113,"Nondurables less food, beverages, and apparel",CUSR0000SANL113,SEASONALLY ADJUSTED INDEX,2018,245.171,248.140,244.987,247.490,250.659,252.144,251.396,251.779,252.711,253.838,247.939,241.044
996,SEHL04,Nonelectric cookware and tableware,CUSR0000SEHL04,SEASONALLY ADJUSTED INDEX,2018,81.288,82.776,84.929,85.497,86.297,83.851,83.383,83.125,83.203,84.724,83.489,83.914
2252,SEHE02,"Propane, kerosene, and firewood",CWSR0000SEHE02,SEASONAL FACTOR,2018,104.417,104.724,104.369,101.416,98.868,97.253,95.744,95.926,96.714,98.343,100.352,101.772
1425,SAC,Commodities,CWSR0000SAC,SEASONAL FACTOR,2019,99.011,99.334,100.015,100.438,100.925,100.834,100.725,100.383,100.180,100.117,99.528,98.552
301,SANL1,Nondurables less food,CUSR0000SANL1,SEASONALLY ADJUSTED INDEX,2019,193.847,196.285,198.329,202.410,202.213,200.291,200.874,199.680,199.238,200.590,200.791,202.573
2437,SERE01,Toys,CWSR0000SERE01,SEASONALLY ADJUSTED INDEX,2019,33.223,32.917,32.515,32.008,31.965,32.021,31.702,31.728,31.485,31.245,30.952,30.752
1386,SA0L5,All items less medical care,CWSR0000SA0L5,SEASONALLY ADJUSTED INDEX,2018,233.512,234.176,233.970,234.690,235.234,235.443,235.682,236.265,236.700,237.397,236.925,236.748
1504,SAF1,Food,CWSR0000SAF1,UNADJUSTED INDEX,2018,251.108,250.975,251.062,251.888,251.651,251.849,252.373,252.736,253.093,252.985,253.025,253.826
579,SEFA03,"Rice, pasta, cornmeal",CUSR0000SEFA03,SEASONAL FACTOR,2019,99.450,100.203,100.056,100.015,100.416,100.719,100.884,100.822,99.528,99.231,99.387,99.272
473,SEAD,Girls' apparel,CUSR0000SEAD,UNADJUSTED INDEX,2019,91.797,96.147,94.439,94.585,92.578,96.239,93.289,91.576,96.695,95.866,93.981,94.203
1806,SEAE,Footwear,CWSR0000SEAE,SEASONALLY ADJUSTED INDEX,2018,136.150,136.252,140.027,140.611,140.315,139.660,139.926,138.733,138.288,138.644,138.278,138.176

In [30]:
df_USA_2018_2019.tail(20)

,ITEM,TITLE,series id,DATA TYPE,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
2506,SETG02,Other intercity transportation,CWSR0000SETG02,UNADJUSTED INDEX,2018,160.052,159.111,160.133,161.225,158.995,157.718,160.058,157.398,156.275,155.819,156.009,158.740
2507,SETG02,Other intercity transportation,CWSR0000SETG02,UNADJUSTED INDEX,2019,156.743,156.845,159.700,161.578,161.241,158.708,157.129,157.763,156.600,153.484,155.242,154.162
2508,SS47014,"Gasoline, unleaded regular",CWSR0000SS47014,SEASONALLY ADJUSTED INDEX,2018,231.055,235.014,226.673,234.581,239.084,240.446,237.858,243.710,248.186,249.709,232.792,219.686
2509,SS47014,"Gasoline, unleaded regular",CWSR0000SS47014,SEASONALLY ADJUSTED INDEX,2019,205.313,212.404,225.064,241.765,237.837,226.405,229.757,225.771,226.829,230.192,229.851,238.238
2510,SS47014,"Gasoline, unleaded regular",CWSR0000SS47014,SEASONAL FACTOR,2018,95.331,95.119,98.380,101.177,105.305,105.003,104.530,101.662,100.147,100.025,98.956,94.067
2511,SS47014,"Gasoline, unleaded regular",CWSR0000SS47014,SEASONAL FACTOR,2019,95.407,95.201,98.427,101.205,105.346,105.028,104.528,101.657,100.130,99.984,98.898,94.026
2512,SS47014,"Gasoline, unleaded regular",CWSR0000SS47014,UNADJUSTED INDEX,2018,220.268,223.542,223.000,237.343,251.767,252.475,248.632,247.759,248.550,249.771,230.362,206.652
2513,SS47014,"Gasoline, unleaded regular",CWSR0000SS47014,UNADJUSTED INDEX,2019,195.883,202.212,221.524,244.679,250.551,237.788,240.161,229.511,227.124,230.154,227.319,224.006
2514,SS47015,"Gasoline, unleaded midgrade",CWSR0000SS47015,SEASONALLY ADJUSTED INDEX,2018,249.636,255.496,250.450,256.698,260.064,263.610,262.904,263.746,266.081,268.925,256.664,244.002
2515,SS47015,"Gasoline, unleaded midgrade",CWSR0000SS47015,SEASONALLY ADJUSTED INDEX,2019,231.620,236.481,248.207,266.204,261.078,252.337,253.724,248.670,248.965,254.902,255.823,263.820
2516,SS47015,"Gasoline, unleaded midgrade",CWSR0000SS47015,SEASONAL FACTOR,2018,96.285,95.570,97.556,100.339,104.574,103.817,102.789,101.999,101.504,100.888,99.379,95.381
2517,SS47015,"Gasoline, unleaded midgrade",CWSR0000SS47015,SEASONAL FACTOR,2019,95.803,95.427,97.904,100.245,104.663,103.724,103.798,101.979,101.517,100.696,99.474,94.744
2518,SS47015,"Gasoline, unleaded midgrade",CWSR0000SS47015,UNADJUSTED INDEX,2018,240.362,244.178,244.328,257.568,271.959,273.673,270.237,269.018,270.083,271.312,255.071,232.733
2519,SS47015,"Gasoline, unleaded midgrade",CWSR0000SS47015,UNADJUSTED INDEX,2019,221.899,225.667,243.005,266.857,273.253,261.734,263.361,253.591,252.741,256.675,254.477,249.953
2520,SS47016,"Gasoline, unleaded premium",CWSR0000SS47016,SEASONALLY ADJUSTED INDEX,2018,243.260,250.204,246.284,250.991,254.346,257.161,255.860,257.739,259.879,263.183,252.688,241.892
2521,SS47016,"Gasoline, unleaded premium",CWSR0000SS47016,SEASONALLY ADJUSTED INDEX,2019,230.210,234.790,243.253,260.100,257.136,248.630,248.746,245.122,246.002,251.981,253.933,259.037
2522,SS47016,"Gasoline, unleaded premium",CWSR0000SS47016,SEASONAL FACTOR,2018,96.595,95.676,97.439,100.549,104.266,103.642,102.828,101.652,101.248,100.912,99.438,95.908
2523,SS47016,"Gasoline, unleaded premium",CWSR0000SS47016,SEASONAL FACTOR,2019,96.114,95.333,97.920,100.535,104.346,103.545,103.534,101.747,101.174,101.012,99.480,95.314
2524,SS47016,"Gasoline, unleaded premium",CWSR0000SS47016,UNADJUSTED INDEX,2018,234.978,239.384,239.977,252.370,265.196,266.526,263.095,261.998,263.122,265.584,251.268,231.993
2525,SS47016,"Gasoline, unleaded premium",CWSR0000SS47016,UNADJUSTED INDEX,2019,221.264,223.833,238.192,261.492,268.311,257.445,257.537,249.403,248.891,254.532,252.612,246.899

In [31]:
for column in df_USA_2018_2019.columns:
    print(check_data_type(df_USA_2018_2019, column), sep = '\n')
    print("Is there any missing NA values for US dataset: ", check_for_na(df_USA_2018_2019, column))

ITEM data type is: object
Is there any missing NA values for US dataset:  False
TITLE data type is: object
Is there any missing NA values for US dataset:  False
series id data type is: object
Is there any missing NA values for US dataset:  False
DATA TYPE data type is: object
Is there any missing NA values for US dataset:  False
YEAR data type is: int64
Is there any missing NA values for US dataset:  False
JAN data type is: float64
Is there any missing NA values for US dataset:  False
FEB data type is: float64
Is there any missing NA values for US dataset:  False
MAR data type is: float64
Is there any missing NA values for US dataset:  False
APR data type is: float64
Is there any missing NA values for US dataset:  False
MAY data type is: float64
Is there any missing NA values for US dataset:  False
JUN data type is: float64
Is there any missing NA values for US dataset:  False
JUL data type is: float64
Is there any missing NA values for US dataset:  False
AUG data type is: float64
Is there any missing NA values for US dataset:  False
SEP data type is: float64
Is there any missing NA values for US dataset:  False
OCT data type is: float64
Is there any missing NA values for US dataset:  False
NOV data type is: float64
Is there any missing NA values for US dataset:  False
DEC data type is: float64
Is there any missing NA values for US dataset:  False

In [32]:
#there are no missing values in the US dataset and all CPI values are float values while YEAR is an integer value that will be converted to datetime format in pandas

In [33]:
for column in df_USA_2018_2019.columns:
    if df_USA_2018_2019[column].dtype == float:
        print(column, " is greater than 0: ", test_unit_less_than_or_greater_than(df_USA_2018_2019, column, 0, "greater_than"))
        print(column, " is less than 1000: ", test_unit_less_than_or_greater_than(df_USA_2018_2019, column, 1000, "less_than"))

JAN  is greater than 0:  True
JAN  is less than 1000:  True
FEB  is greater than 0:  True
FEB  is less than 1000:  True
MAR  is greater than 0:  True
MAR  is less than 1000:  True
APR  is greater than 0:  True
APR  is less than 1000:  True
MAY  is greater than 0:  True
MAY  is less than 1000:  True
JUN  is greater than 0:  True
JUN  is less than 1000:  True
JUL  is greater than 0:  True
JUL  is less than 1000:  True
AUG  is greater than 0:  True
AUG  is less than 1000:  True
SEP  is greater than 0:  True
SEP  is less than 1000:  True
OCT  is greater than 0:  True
OCT  is less than 1000:  True
NOV  is greater than 0:  True
NOV  is less than 1000:  True
DEC  is greater than 0:  True
DEC  is less than 1000:  True

In [34]:
df_USA_CPI_Formatted = manipulate_data(df_USA_2018_2019, 'USA')

/Users/richardwcheng/Documents/GoodsComparison2018Tariffs/notebooks/../src/data/make_dataset.py:67: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_USA_Single_Columns_for_2018_2019['REF_DATE'] = pd.to_datetime(df_USA_Single_Columns_for_2018_2019['REF_DATE'])

In [35]:
df_USA_CPI_Formatted.head()

,Airline fares,Alcoholic beverages,Alcoholic beverages at home,All items,All items less energy,All items less food,All items less food and energy,All items less food and shelter,"All items less food, shelter, and energy","All items less food, shelter, energy, and used cars and trucks",...,Water and sewerage maintenance,Window and floor coverings and other linens,Women's and girls' apparel,Women's apparel,Women's dresses,Women's footwear,Women's outerwear,Women's suits and separates,"Women's underwear, nightwear, swimwear, and accessories",REF_DATE
0,266.9715,249.1495,205.3635,245.9420,250.7335,244.8475,251.1065,224.497,228.439,233.930,...,536.9055,58.4075,109.9720,112.9810,121.9400,125.9325,99.1620,79.7240,108.2020,2018-01-01
1,267.5715,249.5565,205.7950,246.6060,251.1070,245.6380,251.5730,225.385,228.910,234.432,...,538.8085,58.7750,110.8680,114.7320,124.2860,128.1450,100.7195,81.1365,107.9710,2018-02-01
2,269.0340,249.9520,205.8880,246.5580,251.5585,245.5655,252.0890,224.982,229.218,234.804,...,540.0200,58.4490,110.5010,113.6695,124.7015,131.0840,103.1610,79.9705,106.4075,2018-03-01
3,267.5340,250.2890,205.9995,247.2425,251.9250,246.2830,252.4365,225.551,229.282,234.905,...,541.4110,58.5845,111.6685,114.5005,127.7945,128.8445,108.0825,80.7635,106.2595,2018-04-01
4,265.3995,250.1165,205.8720,247.8040,252.3285,246.9400,252.9220,226.008,229.491,235.070,...,542.9205,58.3195,112.3755,115.4285,126.5950,128.4360,104.3915,82.2760,107.2545,2018-05-01

In [36]:
for column in df_USA_CPI_Formatted.columns:
    print(column)

Airline fares
Alcoholic beverages
Alcoholic beverages at home
All items
All items less energy
All items less food
All items less food and energy
All items less food and shelter
All items less food, shelter, and energy
All items less food, shelter, energy, and used cars and trucks
All items less medical care
All items less shelter
Apparel
Apparel less footwear
Apples
Appliances
Bacon and related products
Bacon, breakfast sausage, and related products
Beef and veal
Beer, ale, and other malt beverages at home
Beverage materials including coffee and tea
Boys' and girls' footwear
Boys' apparel
Breakfast sausage and related products
Butter
Butter and margarine
Cable, satellite, and live streaming television service
Canned fruits
Canned fruits and vegetables
Canned vegetables
Car and truck rental
Carbonated drinks
Cereals and bakery products
Cereals and cereal products
Citrus fruits
Coffee
College tuition and fees
Commodities
Commodities less food
Commodities less food and beverages
Commodities less food and energy commodities
Commodities less food, energy, and used cars and trucks
Communication
Crackers, bread, and cracker products
Dairy and related products
Day care and preschool
Delivery services
Dental services
Durables
Education
Education and communication
Education and communication commodities
Education and communication services
Electricity
Elementary and high school tuition and fees
Energy
Energy commodities
Energy services
Fats and oils
Fish and seafood
Flour and prepared flour mixes
Food
Food and beverages
Food at home
Footwear
Frankfurters
Fresh biscuits, rolls, muffins
Fresh fruits
Fresh fruits and vegetables
Fresh milk other than whole
Fresh vegetables
Fresh whole milk
Frozen and freeze dried prepared foods
Frozen and refrigerated bakery products, pies, tarts, turnovers
Frozen fish and seafood
Frozen fruits and vegetables
Frozen vegetables
Fruits and vegetables
Fuel oil and other fuels
Fuels and utilities
Gasoline (all types)
Gasoline, unleaded midgrade
Gasoline, unleaded premium
Gasoline, unleaded regular
Girls' apparel
Ham
Ham, excluding canned
Household energy
Household furnishings and operations
Household furnishings and supplies
Housing
Housing at school, excluding board
Ice cream and related products
Indoor plants and flowers
Infants' and toddlers' apparel
Information and information processing
Information technology commodities
Information technology, hardware and services
Jewelry
Jewelry and watches
Juices and nonalcoholic drinks
Lettuce
Lodging away from home
Major appliances
Meats
Meats, poultry, and fish
Meats, poultry, fish, and eggs
Medical care
Medical care services
Men's and boys' apparel
Men's apparel
Men's pants and shorts
Men's shirts and sweaters
Men's suits, sport coats, and outerwear
Milk
Motor fuel
Motor vehicle insurance
New and used motor vehicles
New cars
New trucks
New vehicles
Nonalcoholic beverages and beverage materials
Nondurables
Nondurables less food
Nondurables less food and apparel
Nondurables less food and beverages
Nondurables less food, beverages, and apparel
Nonelectric cookware and tableware
Nonfrozen noncarbonated juices and drinks
Nursing homes and adult day services
Oranges, including tangerines
Other bakery products
Other condiments
Other dairy and related products
Other fats and oils including peanut butter
Other food at home
Other foods
Other fresh fruits
Other fresh vegetables
Other furniture
Other goods
Other goods and services
Other household equipment and furnishings
Other intercity transportation
Other linens
Other lodging away from home including hotels and motels
Other meats
Other miscellaneous foods
Other pork including roasts, steaks, and ribs
Other processed fruits and vegetables including dried
Other recreation services
Other recreational goods
Other services
Other sweets
Other uncooked poultry including turkey
Other video equipment
Outdoor equipment and supplies
Owners' equivalent rent of primary residence
Owners' equivalent rent of residences
Parking fees and tolls
Pet services including veterinary
Pets, pet products and services
Photographic equipment
Photographic equipment and supplies
Photography
Pork
Postage
Postage and delivery services
Potatoes
Prepared salads
Private transportation
Processed fish and seafood
Processed fruits and vegetables
Professional services
Propane, kerosene, and firewood
Public transportation
Recreation
Recreation commodities
Recreation services
Rent of primary residence
Rent of shelter
Rice, pasta, cornmeal
Roasted coffee
Salad dressing
Salt and other seasonings and spices
Sauces and gravies
Services
Services less energy services
Services less medical care services
Services less rent of shelter
Shelf stable fish and seafood
Shelter
Snacks
Soups
Spices, seasonings, condiments, sauces
Stationery, stationery supplies, gift wrap
Sugar and sugar substitutes
Televisions
Tomatoes
Tools, hardware and supplies
Tools, hardware, outdoor equipment and supplies
Toys
Toys, games, hobbies and playground equipment
Transportation
Transportation commodities less motor fuel
Transportation services
Tuition, other school fees, and childcare
Uncooked beef roasts
Uncooked beef steaks
Used cars and trucks
Utilities and public transportation
Utility (piped) gas service
Veterinarian services
Video and audio
Video and audio products
Video and audio services
Water and sewer and trash collection services
Water and sewerage maintenance
Window and floor coverings and other linens
Women's and girls' apparel
Women's apparel
Women's dresses
Women's footwear
Women's outerwear
Women's suits and separates
Women's underwear, nightwear, swimwear, and accessories
REF_DATE

In [63]:
#see how Education has risen in 2018 and 2019 since 1984 which is the base value of 100
print("Education in the year 2018-2019", " is greater than 0: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Education", 0, "greater_than"))
print("Education in the year 2018-2019", " is greater than 150: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Education", 150, "greater_than"))
print("Education in the year 2018-2019", " is greater than 200: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Education", 200, "greater_than"))
print("Education in the year 2018-2019", " is greater than 250: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Education", 250, "greater_than"))
print("Education in the year 2018-2019", " is greater than 300: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Education", 300, "greater_than"))
print("Education in the year 2018-2019", " is less than 500: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Education", 500, "less_than"))
print("Education in the year 2018-2019", " is less than 800: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Education", 800, "less_than"))

print(df_USA_CPI_Formatted["Education"].describe())

Education in the year 2018-2019  is greater than 0:  True
Education in the year 2018-2019  is greater than 150:  True
Education in the year 2018-2019  is greater than 200:  True
Education in the year 2018-2019  is greater than 250:  True
Education in the year 2018-2019  is greater than 300:  False
Education in the year 2018-2019  is less than 500:  True
Education in the year 2018-2019  is less than 800:  True
count     24.000000
mean     260.174083
std        3.981642
min      253.945500
25%      256.489625
50%      260.353750
75%      263.534375
max      265.933500
Name: Education, dtype: float64

In [62]:
#see how Energy has risen in 2018 and 2019 since 1984 which is the base value of 100
print("Energy in the year 2018-2019", " is greater than 0: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Energy", 0, "greater_than"))
print("Energy in the year 2018-2019", " is greater than 150: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Energy", 150, "greater_than"))
print("Energy in the year 2018-2019", " is greater than 200: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Energy", 200, "greater_than"))
print("Energy in the year 2018-2019", " is greater than 250: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Energy", 250, "greater_than"))
print("Energy in the year 2018-2019", " is less than 500: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Energy", 500, "less_than"))
print("Energy in the year 2018-2019", " is less than 800: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Energy", 800, "less_than"))

print(df_USA_CPI_Formatted["Energy"].describe())

Energy in the year 2018-2019  is greater than 0:  True
Energy in the year 2018-2019  is greater than 150:  True
Energy in the year 2018-2019  is greater than 200:  True
Energy in the year 2018-2019  is greater than 250:  False
Energy in the year 2018-2019  is less than 500:  True
Energy in the year 2018-2019  is less than 800:  True
count     24.000000
mean     217.361562
std        4.816284
min      206.152500
25%      213.845500
50%      217.597750
75%      220.939375
max      226.039000
Name: Energy, dtype: float64

In [64]:
#see how All-items has risen in 2018 and 2019 since 1984 which is the base value of 100
print("All items in the year 2018-2019", " is greater than 0: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "All items", 0, "greater_than"))
print("All items in the year 2018-2019", " is greater than 150: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "All items", 150, "greater_than"))
print("All items in the year 2018-2019", " is greater than 200: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "All items", 200, "greater_than"))
print("All items in the year 2018-2019", " is greater than 250: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "All items", 250, "greater_than"))
print("All items in the year 2018-2019", " is less than 500: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "All items", 500, "less_than"))
print("All items in the year 2018-2019", " is less than 800: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "All items", 800, "less_than"))
print(df_USA_CPI_Formatted["All items"].describe())

All items in the year 2018-2019  is greater than 0:  True
All items in the year 2018-2019  is greater than 150:  True
All items in the year 2018-2019  is greater than 200:  True
All items in the year 2018-2019  is greater than 250:  False
All items in the year 2018-2019  is less than 500:  True
All items in the year 2018-2019  is less than 800:  True
count     24.000000
mean     250.275646
std        2.673634
min      245.942000
25%      248.193625
50%      249.730250
75%      252.194750
max      255.434500
Name: All items, dtype: float64

In [40]:
df_Canada_2018_2019.head()

,REF_DATE,GEO,DGUID,Products and product groups,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2018-01-01,Canada,2016A000011124,All-items,2002=100,17,units,0,v41690973,2.2,131.7,NaN,NaN,NaN,1
1,2018-01-01,Canada,2016A000011124,Food,2002=100,17,units,0,v41690974,2.3,144.7,NaN,NaN,NaN,1
2,2018-01-01,Canada,2016A000011124,Food purchased from stores,2002=100,17,units,0,v41690975,2.4,142.6,NaN,NaN,NaN,1
3,2018-01-01,Canada,2016A000011124,Meat,2002=100,17,units,0,v41690976,2.5,156.2,NaN,NaN,NaN,1
4,2018-01-01,Canada,2016A000011124,Fresh or frozen meat (excluding poultry),2002=100,17,units,0,v41690977,2.6,164.2,NaN,NaN,NaN,1

In [41]:
for column in df_Canada_2018_2019.columns:
    print(check_data_type(df_Canada_2018_2019, column), sep = '\n')
    print("Is there any missing NA values: ", check_for_na(df_Canada_2018_2019, column))

REF_DATE data type is: object
Is there any missing NA values:  False
GEO data type is: object
Is there any missing NA values:  False
DGUID data type is: object
Is there any missing NA values:  True
Products and product groups data type is: object
Is there any missing NA values:  False
UOM data type is: object
Is there any missing NA values:  False
UOM_ID data type is: int64
Is there any missing NA values:  False
SCALAR_FACTOR data type is: object
Is there any missing NA values:  False
SCALAR_ID data type is: int64
Is there any missing NA values:  False
VECTOR data type is: object
Is there any missing NA values:  False
COORDINATE data type is: float64
Is there any missing NA values:  False
VALUE data type is: float64
Is there any missing NA values:  False
STATUS data type is: float64
Is there any missing NA values:  True
SYMBOL data type is: float64
Is there any missing NA values:  True
TERMINATED data type is: object
Is there any missing NA values:  True
DECIMALS data type is: int64
Is there any missing NA values:  False

In [42]:
#There seems to be missing values in DGUID, STATUS, SYMBOL, and TERMINATED but we are not using those columns and dropping them when we manipulate the data

In [43]:
df_Canada_CPI_Formatted = manipulate_data(df_Canada_2018_2019, 'Canada')

In [44]:
#see the range of CPI index for Canada in 2018 and 2019 for any item
print("VALUE column for all types of products in the year 2018-2019", " is greater than 0: ", test_unit_less_than_or_greater_than(df_Canada_CPI_Formatted, "VALUE", 0, "greater_than"))
print("VALUE column for all types of products in the year 2018-2019", " is greater than 100: ", test_unit_less_than_or_greater_than(df_Canada_CPI_Formatted, "VALUE", 100, "greater_than"))
print("VALUE column for all types of products in the year 2018-2019", " is greater than 140: ", test_unit_less_than_or_greater_than(df_Canada_CPI_Formatted, "VALUE", 140, "greater_than"))
print("VALUE column for all types of products in the year 2018-2019", " is greater than 150: ", test_unit_less_than_or_greater_than(df_Canada_CPI_Formatted, "VALUE", 150, "greater_than"))
print("VALUE column for all types of products in the year 2018-2019", " is greater than 200: ", test_unit_less_than_or_greater_than(df_Canada_CPI_Formatted, "VALUE", 200, "greater_than"))
print("VALUE column for all types of products in the year 2018-2019", " is greater than 250: ", test_unit_less_than_or_greater_than(df_Canada_CPI_Formatted, "VALUE", 250, "greater_than"))
print("VALUE column for all types of products in the year 2018-2019", " is less than 500: ", test_unit_less_than_or_greater_than(df_Canada_CPI_Formatted, "VALUE", 500, "less_than"))
print("VALUE column for all types of products in the year 2018-2019", " is less than 800: ", test_unit_less_than_or_greater_than(df_Canada_CPI_Formatted, "VALUE", 800, "less_than"))

VALUE column for all types of products in the year 2018-2019  is greater than 0:  True
VALUE column for all types of products in the year 2018-2019  is greater than 100:  False
VALUE column for all types of products in the year 2018-2019  is greater than 140:  False
VALUE column for all types of products in the year 2018-2019  is greater than 150:  False
VALUE column for all types of products in the year 2018-2019  is greater than 200:  False
VALUE column for all types of products in the year 2018-2019  is greater than 250:  False
VALUE column for all types of products in the year 2018-2019  is less than 500:  True
VALUE column for all types of products in the year 2018-2019  is less than 800:  True

In [69]:
print("VALUE column for all type of products is between 15 and 260", test_unit_between(df_Canada_CPI_Formatted, "VALUE", 15, 260))

print(df_Canada_CPI_Formatted["VALUE"].describe())
print("Describe Education for Canadian Dataset: ", sep='/n')
print(df_Canada_CPI_Formatted[df_Canada_CPI_Formatted['Products and product groups']=="Education"]["VALUE"].describe())
print("Describe Energy for Canadian Dataset: ", sep='/n')
print(df_Canada_CPI_Formatted[df_Canada_CPI_Formatted['Products and product groups']=="Energy"]["VALUE"].describe())

VALUE column for all type of products is between 15 and 260 True
count    7839.000000
mean      129.418692
std        32.659752
min        17.200000
25%       105.100000
50%       130.330769
75%       150.000000
max       253.881818
Name: VALUE, dtype: float64
Describe Education for Canadian Dataset:
count     24.000000
mean     160.490152
std        2.330904
min      157.100000
25%      157.377273
50%      161.772727
75%      161.993182
max      162.936364
Name: VALUE, dtype: float64
Describe Energy for Canadian Dataset:
count     24.000000
mean     166.395192
std        5.763791
min      153.369231
25%      163.671154
50%      166.034615
75%      171.515385
max      174.592308
Name: VALUE, dtype: float64

In [ ]:
#It seems like the values for American dataset are much higher than the Canadian dataset. This is because the base year for the American dataset is 1984 while the base year for the Canadian dataset is 2002. This means that the Canadian dataset is indexed to 2002 = 100 while the American dataset is indexed to 1984 = 100. This means that the American dataset will have higher values than the Canadian dataset.
#It may be important to standardize the datasets when doing differences in differences for eventual comparison purposes but the numbers of CPI index appear to make sense.

In [45]:
df_Canada_CPI_Formatted.head()

  Products and product groups   REF_DATE  VALUE
0          Air transportation 2018-01-01  151.3
1          Air transportation 2018-02-01  150.8
2          Air transportation 2018-03-01  155.1
3          Air transportation 2018-04-01  150.7
4          Air transportation 2018-05-01  151.2

In [46]:
save_data(df_USA_CPI_Formatted, '../data/processed/USA_CPI_Processed_2018_2019.csv')
save_data(df_Canada_CPI_Formatted, '../data/processed/Canada_CPI_Processed_2018_2019.csv')