In [14]:
import pandas as pd
import importlib
import sys
sys.path.append('../src')
import data
importlib.reload(data)
from data import save_data, load_data, manipulate_data, check_for_na, check_data_type, test_unit_dtype, test_unit_less_than_or_greater_than, test_unit_between

In [15]:
df_USA_2018_2019 = load_data('../data/raw/USACPI_2018_2019.csv')
df_Canada_2018_2019 = load_data('../data/raw/CanadaCPI_2018_2019.csv')

In [16]:
df_USA_2018_2019.head(20)

,ITEM,TITLE,series id,DATA TYPE,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
0,SA0,All items,CUSR0000SA0,SEASONALLY ADJUSTED INDEX,2018,248.859,249.529,249.577,250.227,250.792,251.018,251.214,251.663,252.182,252.772,252.594,252.767
1,SA0,All items,CUSR0000SA0,SEASONALLY ADJUSTED INDEX,2019,252.718,253.322,254.202,255.211,255.290,255.159,255.685,256.059,256.511,257.244,257.803,258.616
2,SA0,All items,CUSR0000SA0,SEASONAL FACTOR,2018,99.601,99.784,99.991,100.127,100.317,100.387,100.315,100.192,100.102,100.045,99.780,99.393
3,SA0,All items,CUSR0000SA0,SEASONAL FACTOR,2019,99.602,99.784,100.000,100.132,100.314,100.386,100.347,100.195,100.097,100.040,99.769,99.365
4,SA0,All items,CUSR0000SA0,UNADJUSTED INDEX,2018,247.867,248.991,249.554,250.546,251.588,251.989,252.006,252.146,252.439,252.885,252.038,251.233
5,SA0,All items,CUSR0000SA0,UNADJUSTED INDEX,2019,251.712,252.776,254.202,255.548,256.092,256.143,256.571,256.558,256.759,257.346,257.208,256.974
6,SA0E,Energy,CUSR0000SA0E,SEASONALLY ADJUSTED INDEX,2018,216.855,220.141,215.720,219.165,221.045,220.947,219.929,222.781,223.955,226.022,218.500,213.630
7,SA0E,Energy,CUSR0000SA0E,SEASONALLY ADJUSTED INDEX,2019,206.808,209.143,214.305,222.300,219.682,213.339,215.128,213.335,213.647,216.546,217.228,221.757
8,SA0E,Energy,CUSR0000SA0E,SEASONAL FACTOR,2018,97.145,96.992,98.532,99.847,102.608,103.707,103.264,101.866,100.987,99.883,98.815,96.384
9,SA0E,Energy,CUSR0000SA0E,SEASONAL FACTOR,2019,96.980,96.938,98.796,100.090,102.773,103.766,103.423,101.708,100.829,99.910,98.807,96.043
10,SA0E,Energy,CUSR0000SA0E,UNADJUSTED INDEX,2018,210.663,213.519,212.554,218.830,226.810,229.137,227.107,226.939,226.165,225.757,215.910,205.905
11,SA0E,Energy,CUSR0000SA0E,UNADJUSTED INDEX,2019,200.563,202.740,211.724,222.499,225.773,221.373,222.492,216.978,215.418,216.351,214.636,212.982
12,SA0L1,All items less food,CUSR0000SA0L1,SEASONALLY ADJUSTED INDEX,2018,248.301,249.089,249.128,249.801,250.452,250.666,250.826,251.291,251.834,252.534,252.220,252.270
13,SA0L1,All items less food,CUSR0000SA0L1,SEASONALLY ADJUSTED INDEX,2019,252.117,252.695,253.644,254.858,254.878,254.715,255.301,255.702,256.132,256.888,257.440,258.297
14,SA0L1,All items less food,CUSR0000SA0L1,SEASONAL FACTOR,2018,99.541,99.751,99.990,100.127,100.352,100.442,100.355,100.213,100.112,100.040,99.777,99.340
15,SA0L1,All items less food,CUSR0000SA0L1,SEASONAL FACTOR,2019,99.547,99.755,100.000,100.132,100.346,100.436,100.386,100.214,100.105,100.033,99.767,99.310
16,SA0L1,All items less food,CUSR0000SA0L1,UNADJUSTED INDEX,2018,247.161,248.469,249.102,250.117,251.333,251.775,251.716,251.827,252.116,252.636,251.657,250.605
17,SA0L1,All items less food,CUSR0000SA0L1,UNADJUSTED INDEX,2019,250.974,252.077,253.643,255.194,255.759,255.825,256.286,256.250,256.401,256.973,256.839,256.516
18,SA0L12,All items less food and shelter,CUSR0000SA0L12,SEASONALLY ADJUSTED INDEX,2018,224.497,225.385,224.982,225.551,226.008,226.152,225.995,226.242,226.799,227.421,226.586,226.262
19,SA0L12,All items less food and shelter,CUSR0000SA0L12,SEASONALLY ADJUSTED INDEX,2019,225.650,226.014,226.924,228.179,227.825,227.210,227.691,228.005,228.176,229.074,229.538,230.497

In [17]:
df_USA_2018_2019.sample(20)

,ITEM,TITLE,series id,DATA TYPE,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
456,SEAC03,Women's suits and separates,CUSR0000SEAC03,SEASONALLY ADJUSTED INDEX,2018,79.349,80.722,79.877,80.812,82.323,81.608,78.806,75.810,77.847,77.908,77.260,76.472
2507,SETG02,Other intercity transportation,CWSR0000SETG02,UNADJUSTED INDEX,2019,156.743,156.845,159.700,161.578,161.241,158.708,157.129,157.763,156.600,153.484,155.242,154.162
1041,SERA,Video and audio,CUSR0000SERA,SEASONAL FACTOR,2019,99.589,100.220,100.538,100.376,100.319,100.232,100.093,99.989,99.845,99.688,99.671,99.469
23,SA0L12,All items less food and shelter,CUSR0000SA0L12,UNADJUSTED INDEX,2019,224.129,225.199,226.909,228.655,229.061,228.659,228.952,228.658,228.479,229.222,228.802,228.109
1482,SAEC,Education and communication commodities,CWSR0000SAEC,SEASONALLY ADJUSTED INDEX,2018,77.825,77.656,77.514,77.500,77.710,76.967,76.645,76.566,76.708,75.899,75.033,74.880
1533,SAF11211,Meats,CWSR0000SAF11211,SEASONAL FACTOR,2019,98.880,98.820,99.531,100.120,100.315,100.765,101.121,101.000,100.521,100.364,99.561,98.998
622,SEFD01,"Bacon, breakfast sausage, and related products",CUSR0000SEFD01,UNADJUSTED INDEX,2018,160.862,160.153,161.054,158.816,158.053,156.149,159.197,159.754,159.969,156.945,156.348,154.712
845,SEFT02,Frozen and freeze dried prepared foods,CUSR0000SEFT02,UNADJUSTED INDEX,2019,164.873,167.445,165.470,168.036,166.817,167.524,167.637,165.816,164.947,167.453,168.087,166.066
2043,SEFL,Fresh vegetables,CWSR0000SEFL,SEASONAL FACTOR,2019,102.375,100.793,99.645,99.603,99.580,99.352,99.656,99.562,99.033,100.089,99.693,100.834
2312,SEHK01,Major appliances,CWSR0000SEHK01,SEASONAL FACTOR,2018,100.598,99.516,100.755,101.577,101.489,100.709,100.443,100.016,99.916,99.805,96.716,98.312
983,SEHK01,Major appliances,CUSR0000SEHK01,UNADJUSTED INDEX,2019,88.056,86.279,85.227,86.749,86.593,85.377,83.932,83.502,84.541,82.320,79.914,79.224
54,SA0LE,All items less energy,CUSR0000SA0LE,SEASONALLY ADJUSTED INDEX,2018,254.078,254.494,254.985,255.363,255.802,256.063,256.380,256.595,257.053,257.502,258.050,258.726
1165,SETG01,Airline fares,CUSR0000SETG01,SEASONALLY ADJUSTED INDEX,2019,258.962,260.822,263.360,264.063,268.851,268.142,265.083,267.484,270.922,265.541,264.529,262.021
548,SEEC02,Delivery services,CUSR0000SEEC02,SEASONAL FACTOR,2018,101.753,101.201,100.972,100.322,100.316,100.068,100.088,99.836,99.497,99.116,98.648,98.219
956,SEHH,Window and floor coverings and other linens,CUSR0000SEHH,SEASONAL FACTOR,2018,101.469,101.214,100.739,100.257,99.562,99.022,99.533,99.757,100.706,101.229,98.858,97.814
1130,SETA02,Used cars and trucks,CUSR0000SETA02,SEASONAL FACTOR,2018,98.554,99.369,101.215,101.082,99.981,100.825,102.237,102.174,98.692,98.700,98.746,98.494
335,SARC,Recreation commodities,CUSR0000SARC,UNADJUSTED INDEX,2019,80.573,80.156,80.108,80.044,79.928,79.875,79.606,79.605,79.698,79.996,79.889,79.380
237,SAG,Other goods and services,CUSR0000SAG,SEASONAL FACTOR,2019,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000
637,SEFE,Other meats,CUSR0000SEFE,SEASONALLY ADJUSTED INDEX,2019,222.298,224.404,223.422,223.514,224.389,224.440,225.502,226.541,225.779,225.784,226.652,226.132
1220,SS07021,Frozen fish and seafood,CUSR0000SS07021,SEASONAL FACTOR,2018,99.785,99.206,97.936,99.431,100.726,99.963,100.751,100.481,100.388,100.810,100.851,99.887

In [18]:
df_USA_2018_2019.tail(20)

,ITEM,TITLE,series id,DATA TYPE,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
2506,SETG02,Other intercity transportation,CWSR0000SETG02,UNADJUSTED INDEX,2018,160.052,159.111,160.133,161.225,158.995,157.718,160.058,157.398,156.275,155.819,156.009,158.740
2507,SETG02,Other intercity transportation,CWSR0000SETG02,UNADJUSTED INDEX,2019,156.743,156.845,159.700,161.578,161.241,158.708,157.129,157.763,156.600,153.484,155.242,154.162
2508,SS47014,"Gasoline, unleaded regular",CWSR0000SS47014,SEASONALLY ADJUSTED INDEX,2018,231.055,235.014,226.673,234.581,239.084,240.446,237.858,243.710,248.186,249.709,232.792,219.686
2509,SS47014,"Gasoline, unleaded regular",CWSR0000SS47014,SEASONALLY ADJUSTED INDEX,2019,205.313,212.404,225.064,241.765,237.837,226.405,229.757,225.771,226.829,230.192,229.851,238.238
2510,SS47014,"Gasoline, unleaded regular",CWSR0000SS47014,SEASONAL FACTOR,2018,95.331,95.119,98.380,101.177,105.305,105.003,104.530,101.662,100.147,100.025,98.956,94.067
2511,SS47014,"Gasoline, unleaded regular",CWSR0000SS47014,SEASONAL FACTOR,2019,95.407,95.201,98.427,101.205,105.346,105.028,104.528,101.657,100.130,99.984,98.898,94.026
2512,SS47014,"Gasoline, unleaded regular",CWSR0000SS47014,UNADJUSTED INDEX,2018,220.268,223.542,223.000,237.343,251.767,252.475,248.632,247.759,248.550,249.771,230.362,206.652
2513,SS47014,"Gasoline, unleaded regular",CWSR0000SS47014,UNADJUSTED INDEX,2019,195.883,202.212,221.524,244.679,250.551,237.788,240.161,229.511,227.124,230.154,227.319,224.006
2514,SS47015,"Gasoline, unleaded midgrade",CWSR0000SS47015,SEASONALLY ADJUSTED INDEX,2018,249.636,255.496,250.450,256.698,260.064,263.610,262.904,263.746,266.081,268.925,256.664,244.002
2515,SS47015,"Gasoline, unleaded midgrade",CWSR0000SS47015,SEASONALLY ADJUSTED INDEX,2019,231.620,236.481,248.207,266.204,261.078,252.337,253.724,248.670,248.965,254.902,255.823,263.820
2516,SS47015,"Gasoline, unleaded midgrade",CWSR0000SS47015,SEASONAL FACTOR,2018,96.285,95.570,97.556,100.339,104.574,103.817,102.789,101.999,101.504,100.888,99.379,95.381
2517,SS47015,"Gasoline, unleaded midgrade",CWSR0000SS47015,SEASONAL FACTOR,2019,95.803,95.427,97.904,100.245,104.663,103.724,103.798,101.979,101.517,100.696,99.474,94.744
2518,SS47015,"Gasoline, unleaded midgrade",CWSR0000SS47015,UNADJUSTED INDEX,2018,240.362,244.178,244.328,257.568,271.959,273.673,270.237,269.018,270.083,271.312,255.071,232.733
2519,SS47015,"Gasoline, unleaded midgrade",CWSR0000SS47015,UNADJUSTED INDEX,2019,221.899,225.667,243.005,266.857,273.253,261.734,263.361,253.591,252.741,256.675,254.477,249.953
2520,SS47016,"Gasoline, unleaded premium",CWSR0000SS47016,SEASONALLY ADJUSTED INDEX,2018,243.260,250.204,246.284,250.991,254.346,257.161,255.860,257.739,259.879,263.183,252.688,241.892
2521,SS47016,"Gasoline, unleaded premium",CWSR0000SS47016,SEASONALLY ADJUSTED INDEX,2019,230.210,234.790,243.253,260.100,257.136,248.630,248.746,245.122,246.002,251.981,253.933,259.037
2522,SS47016,"Gasoline, unleaded premium",CWSR0000SS47016,SEASONAL FACTOR,2018,96.595,95.676,97.439,100.549,104.266,103.642,102.828,101.652,101.248,100.912,99.438,95.908
2523,SS47016,"Gasoline, unleaded premium",CWSR0000SS47016,SEASONAL FACTOR,2019,96.114,95.333,97.920,100.535,104.346,103.545,103.534,101.747,101.174,101.012,99.480,95.314
2524,SS47016,"Gasoline, unleaded premium",CWSR0000SS47016,UNADJUSTED INDEX,2018,234.978,239.384,239.977,252.370,265.196,266.526,263.095,261.998,263.122,265.584,251.268,231.993
2525,SS47016,"Gasoline, unleaded premium",CWSR0000SS47016,UNADJUSTED INDEX,2019,221.264,223.833,238.192,261.492,268.311,257.445,257.537,249.403,248.891,254.532,252.612,246.899

In [19]:
for column in df_USA_2018_2019.columns:
    print(check_data_type(df_USA_2018_2019, column), sep = '\n')
    print("Is there any missing NA values: ", check_for_na(df_USA_2018_2019, column))

ITEM data type is: object
Is there any missing NA values:  False
TITLE data type is: object
Is there any missing NA values:  False
series id data type is: object
Is there any missing NA values:  False
DATA TYPE data type is: object
Is there any missing NA values:  False
YEAR data type is: int64
Is there any missing NA values:  False
JAN data type is: float64
Is there any missing NA values:  False
FEB data type is: float64
Is there any missing NA values:  False
MAR data type is: float64
Is there any missing NA values:  False
APR data type is: float64
Is there any missing NA values:  False
MAY data type is: float64
Is there any missing NA values:  False
JUN data type is: float64
Is there any missing NA values:  False
JUL data type is: float64
Is there any missing NA values:  False
AUG data type is: float64
Is there any missing NA values:  False
SEP data type is: float64
Is there any missing NA values:  False
OCT data type is: float64
Is there any missing NA values:  False
NOV data type is: float64
Is there any missing NA values:  False
DEC data type is: float64
Is there any missing NA values:  False

In [20]:
#there are no missing values in the US dataset and all CPI values are float values while YEAR is an integer value that will be converted to datetime format in pandas

In [21]:
for column in df_USA_2018_2019.columns:
    if df_USA_2018_2019[column].dtype == float:
        print(column, " is greater than 0: ", test_unit_less_than_or_greater_than(df_USA_2018_2019, column, 0, "greater_than"))
        print(column, " is less than 1000: ", test_unit_less_than_or_greater_than(df_USA_2018_2019, column, 1000, "less_than"))

JAN  is greater than 0:  True
JAN  is less than 1000:  True
FEB  is greater than 0:  True
FEB  is less than 1000:  True
MAR  is greater than 0:  True
MAR  is less than 1000:  True
APR  is greater than 0:  True
APR  is less than 1000:  True
MAY  is greater than 0:  True
MAY  is less than 1000:  True
JUN  is greater than 0:  True
JUN  is less than 1000:  True
JUL  is greater than 0:  True
JUL  is less than 1000:  True
AUG  is greater than 0:  True
AUG  is less than 1000:  True
SEP  is greater than 0:  True
SEP  is less than 1000:  True
OCT  is greater than 0:  True
OCT  is less than 1000:  True
NOV  is greater than 0:  True
NOV  is less than 1000:  True
DEC  is greater than 0:  True
DEC  is less than 1000:  True

In [22]:
df_USA_CPI_Formatted = manipulate_data(df_USA_2018_2019, 'USA')

In [23]:
df_USA_CPI_Formatted.head()

,Airline fares,Alcoholic beverages,Alcoholic beverages at home,All items,All items less energy,All items less food,All items less food and energy,All items less food and shelter,"All items less food, shelter, and energy","All items less food, shelter, energy, and used cars and trucks",...,Water and sewer and trash collection services,Water and sewerage maintenance,Window and floor coverings and other linens,Women's and girls' apparel,Women's apparel,Women's dresses,Women's footwear,Women's outerwear,Women's suits and separates,"Women's underwear, nightwear, swimwear, and accessories"
JAN_2018,266.9715,249.1495,205.3635,245.9420,250.7335,244.8475,251.1065,224.497,228.439,233.930,...,232.9735,536.9055,58.4075,109.9720,112.9810,121.9400,125.9325,99.1620,79.7240,108.2020
FEB_2018,267.5715,249.5565,205.7950,246.6060,251.1070,245.6380,251.5730,225.385,228.910,234.432,...,233.7845,538.8085,58.7750,110.8680,114.7320,124.2860,128.1450,100.7195,81.1365,107.9710
MAR_2018,269.0340,249.9520,205.8880,246.5580,251.5585,245.5655,252.0890,224.982,229.218,234.804,...,234.2170,540.0200,58.4490,110.5010,113.6695,124.7015,131.0840,103.1610,79.9705,106.4075
APR_2018,267.5340,250.2890,205.9995,247.2425,251.9250,246.2830,252.4365,225.551,229.282,234.905,...,235.0835,541.4110,58.5845,111.6685,114.5005,127.7945,128.8445,108.0825,80.7635,106.2595
MAY_2018,265.3995,250.1165,205.8720,247.8040,252.3285,246.9400,252.9220,226.008,229.491,235.070,...,236.1135,542.9205,58.3195,112.3755,115.4285,126.5950,128.4360,104.3915,82.2760,107.2545

In [25]:
#see how Medical care services has risen in 2018 and 2019 since 1984 which is the base value of 100
print("Medical care services", " is greater than 0: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Medical care services", 0, "greater_than"))
print("Medical care services", " is less than 500: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Medical care services", 500, "less_than"))
print("Medical care services", " is less than 800: ", test_unit_less_than_or_greater_than(df_USA_CPI_Formatted, "Medical care services", 800, "less_than"))

DEC  is greater than 0:  True
DEC  is greater than 0:  False
DEC  is less than 800:  True

In [9]:
df_Canada_2018_2019.head()

,REF_DATE,GEO,DGUID,Products and product groups,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2018-01-01,Canada,2016A000011124,All-items,2002=100,17,units,0,v41690973,2.2,131.7,NaN,NaN,NaN,1
1,2018-01-01,Canada,2016A000011124,Food,2002=100,17,units,0,v41690974,2.3,144.7,NaN,NaN,NaN,1
2,2018-01-01,Canada,2016A000011124,Food purchased from stores,2002=100,17,units,0,v41690975,2.4,142.6,NaN,NaN,NaN,1
3,2018-01-01,Canada,2016A000011124,Meat,2002=100,17,units,0,v41690976,2.5,156.2,NaN,NaN,NaN,1
4,2018-01-01,Canada,2016A000011124,Fresh or frozen meat (excluding poultry),2002=100,17,units,0,v41690977,2.6,164.2,NaN,NaN,NaN,1

In [12]:
df_Canada_CPI_Formatted = manipulate_data(df_Canada_2018_2019, 'Canada')

In [13]:
df_Canada_CPI_Formatted.head()

  Products and product groups   REF_DATE  VALUE
0          Air transportation 2018-01-01  151.3
1          Air transportation 2018-02-01  150.8
2          Air transportation 2018-03-01  155.1
3          Air transportation 2018-04-01  150.7
4          Air transportation 2018-05-01  151.2

In [9]:
save_data(df_USA_CPI_Formatted, '../data/processed/USA_CPI_Processed_2018_2019.csv')
save_data(df_Canada_CPI_Formatted, '../data/processed/Canada_CPI_Processed_2018_2019.csv')